{"name": "Невозможно получить несуществующий заказ.", "status": "passed", "description": "В тесте создается и удаляется заказ. Затем по этому заказу запрашивается информация. Проверяется: ошибка == \"Заказ не найден\" и статус код == 404.", "steps": [{"name": "Получение track_id заказа", "status": "passed", "start": 1721097523656, "stop": 1721097524978}, {"name": "Отмена заказа и подготовка query параметра", "status": "passed", "start": 1721097524978, "stop": 1721097526285}, {"name": "Отправка GET запроса для получения заказа", "status": "passed", "start": 1721097526285, "stop": 1721097527978}, {"name": "Проверка: ошибка == 'Заказ не найден'", "status": "passed", "start": 1721097527978, "stop": 1721097527978}, {"name": "Проверка: код ответа == 404", "status": "passed", "start": 1721097527978, "stop": 1721097527978}], "start": 1721097523656, "stop": 1721097527978, "uuid": "c7b4df87-b2d4-45d7-885a-97b4f2c11309", "historyId": "2dddb2bd653f3b5af3fbef328361c033", "testCaseId": "2dddb2bd653f3b5af3fbef328361c033", "fullName": "tests.test_order_get.TestOrderGet#test_get_order_track_id_does_not_exist_order_not_found", "labels": [{"name": "suite", "value": "GET /api/v1/orders/track"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestOrderGet"}, {"name": "host", "value": "C02DQ0GHMD6R"}, {"name": "thread", "value": "78646-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_get"}]}